// Definição única das entidades de dados experimentais/financeiros.
// Reutilizada por: validação no servidor, formulários genéricos do cliente, folha "Dicionario" do Excel
// e docs/DATA_DICTIONARY.md. Alterar aqui propaga para todas as utilizações.

export type FieldKind = "text" | "longtext" | "int" | "decimal" | "date" | "bool" | "ref" | "enum";

export interface FieldDef {
  kind: FieldKind;
  label: string;
  description?: string;
  unit?: string;
  required?: boolean;
  values?: Record<string, string>; // enum: valor -> rótulo
  ref?: EntityName | "reference"; // kind=ref (tabela de destino)
  private?: boolean; // nunca publicado nem incluído em exportações públicas
  default?: string | number | boolean;
  min?: number;
  max?: number;
}

export interface EntityDef {
  name: EntityName;
  table: string;
  label: string;
  labelPlural: string;
  display: string[]; // campos usados para descrever o registo
  orderBy: string;
  fields: Record<string, FieldDef>;
  immutable?: boolean; // apenas criação e arquivo (ex.: versões de protocolo)
  sheet?: string; // nome da folha Excel
}

export const ORIGINS: Record<string, string> = {
  measured: "Medição direta",
  document: "Documento",
  estimate: "Estimativa",
  literature: "Literatura",
  assumption: "Pressuposto",
};

export const CURRENCY_FIELD: FieldDef = {
  kind: "text",
  label: "Moeda",
  description: "Código ISO 4217 (ex.: AOA, EUR). Totais nunca misturam moedas.",
  required: true,
  default: "AOA",
};

const origin = (def: string): FieldDef => ({
  kind: "enum",
  label: "Origem do dado",
  values: ORIGINS,
  required: true,
  default: def,
  description: "Medição, documento, estimativa, literatura ou pressuposto — estados distintos.",
});

export const ENTITY_NAMES = [
  "protocol_version",
  "variable",
  "location",
  "structure",
  "crop",
  "cycle",
  "field_event",
  "harvest",
  "consumption",
  "labor_entry",
  "asset",
  "expense",
  "allocation",
  "sale",
  "exchange_rate",
  "excerpt",
  "personal_communication",
] as const;
export type EntityName = (typeof ENTITY_NAMES)[number];

export const ENTITIES: Record<EntityName, EntityDef> = {
  protocol_version: {
    name: "protocol_version",
    table: "protocol_version",
    label: "Versão do protocolo",
    labelPlural: "Versões do protocolo",
    display: ["number", "title"],
    orderBy: "number",
    immutable: true,
    fields: {
      number: { kind: "int", label: "Número da versão", required: true, min: 1 },
      title: { kind: "text", label: "Título", required: true },
      effective_from: { kind: "date", label: "Em vigor desde" },
      responsible: { kind: "text", label: "Responsáveis" },
      instruments: { kind: "longtext", label: "Instrumentos e calibração" },
      frequency: { kind: "text", label: "Frequência de recolha" },
      procedures: { kind: "longtext", label: "Procedimentos" },
      exclusion_criteria: { kind: "longtext", label: "Critérios de exclusão" },
      deviations: { kind: "longtext", label: "Desvios conhecidos" },
      supersedes_id: { kind: "ref", ref: "protocol_version", label: "Substitui a versão" },
    },
  },
  variable: {
    name: "variable",
    table: "variable",
    label: "Variável",
    labelPlural: "Dicionário de variáveis",
    display: ["code", "name"],
    orderBy: "code",
    fields: {
      code: { kind: "text", label: "Código", required: true },
      name: { kind: "text", label: "Nome", required: true },
      operational_definition: { kind: "longtext", label: "Definição operacional" },
      role: { kind: "text", label: "Papel" },
      data_type: { kind: "text", label: "Tipo" },
      unit: { kind: "text", label: "Unidade" },
      method: { kind: "text", label: "Método" },
      instrument: { kind: "text", label: "Instrumento" },
      periodicity: { kind: "text", label: "Periodicidade" },
      plausible_min: { kind: "decimal", label: "Mínimo plausível" },
      plausible_max: { kind: "decimal", label: "Máximo plausível" },
      missing_rule: { kind: "text", label: "Regra para ausência" },
      transformation: { kind: "text", label: "Transformação" },
      source: { kind: "text", label: "Fonte" },
      experimental_unit: { kind: "text", label: "Unidade experimental" },
      observation_unit: { kind: "text", label: "Unidade de observação" },
      notes: { kind: "longtext", label: "Observações" },
    },
  },
  location: {
    name: "location",
    table: "location",
    label: "Local",
    labelPlural: "Locais",
    display: ["name"],
    orderBy: "name",
    sheet: "Locais",
    fields: {
      name: { kind: "text", label: "Nome", required: true },
      city: { kind: "text", label: "Cidade" },
      public_label: { kind: "text", label: "Designação pública genérica", description: "Ex.: Luanda. Nunca a morada." },
      description: { kind: "longtext", label: "Características" },
      coords_private: { kind: "text", label: "Coordenadas/morada (privado)", private: true },
      is_public: { kind: "bool", label: "Pode ser apresentado publicamente", default: false },
    },
  },
  structure: {
    name: "structure",
    table: "structure",
    label: "Estrutura",
    labelPlural: "Estruturas",
    display: ["code", "system"],
    orderBy: "code",
    sheet: "Estruturas",
    fields: {
      code: { kind: "text", label: "Código", required: true },
      location_id: { kind: "ref", ref: "location", label: "Local", required: true },
      system: { kind: "text", label: "Sistema de cultivo" },
      levels: { kind: "int", label: "Níveis", min: 0 },
      containers: { kind: "int", label: "Recipientes", min: 0 },
      capacity_plants: { kind: "int", label: "Capacidade (plantas)", min: 0 },
      equipment: { kind: "longtext", label: "Equipamentos" },
      footprint_area_m2: {
        kind: "decimal",
        label: "Área de implantação",
        unit: "m²",
        min: 0,
        description: "Área ocupada no solo. Não multiplicar pelos níveis.",
      },
      cultivation_area_m2: {
        kind: "decimal",
        label: "Área total de cultivo",
        unit: "m²",
        min: 0,
        description: "Soma das superfícies de cultivo de todos os níveis (já agregada).",
      },
      useful_area_m2: { kind: "decimal", label: "Área útil ocupada", unit: "m²", min: 0 },
      circulation_area_m2: { kind: "decimal", label: "Área de circulação", unit: "m²", min: 0 },
      area_notes: { kind: "longtext", label: "Fronteiras dos denominadores de área" },
      in_use_from: { kind: "date", label: "Em uso desde" },
      in_use_to: { kind: "date", label: "Em uso até" },
    },
  },
  crop: {
    name: "crop",
    table: "crop",
    label: "Cultura",
    labelPlural: "Culturas",
    display: ["name", "variety"],
    orderBy: "name",
    sheet: "Culturas",
    fields: {
      name: { kind: "text", label: "Cultura", required: true },
      variety: { kind: "text", label: "Variedade" },
      scientific_name: { kind: "text", label: "Nome científico" },
      seed_supplier: { kind: "text", label: "Fornecedor/marca da semente" },
      notes: { kind: "longtext", label: "Notas" },
    },
  },
  cycle: {
    name: "cycle",
    table: "cycle",
    label: "Ciclo",
    labelPlural: "Ciclos",
    display: ["code"],
    orderBy: "code",
    sheet: "Ciclos",
    fields: {
      code: { kind: "text", label: "Código do ciclo", required: true },
      crop_id: { kind: "ref", ref: "crop", label: "Cultura", required: true },
      structure_id: { kind: "ref", ref: "structure", label: "Estrutura", required: true },
      protocol_version_id: { kind: "ref", ref: "protocol_version", label: "Versão do protocolo" },
      lot: { kind: "text", label: "Lote" },
      sowing_date: { kind: "date", label: "Sementeira" },
      transplant_date: { kind: "date", label: "Transplante" },
      start_date: { kind: "date", label: "Início" },
      end_date: { kind: "date", label: "Fim" },
      initial_plants: { kind: "int", label: "Plantas iniciais", min: 0 },
      substrate: { kind: "text", label: "Substrato" },
      irrigation: { kind: "text", label: "Irrigação" },
      status: {
        kind: "enum",
        label: "Estado",
        required: true,
        default: "planned",
        values: { planned: "Planeado", active: "Em curso", finished: "Concluído", failed: "Perdido/falhado", cancelled: "Cancelado" },
      },
      area_fraction: {
        kind: "decimal",
        label: "Fração da área da estrutura usada",
        unit: "0–1",
        required: true,
        default: "1",
        min: 0,
        max: 1,
        description: "Para ciclos simultâneos na mesma estrutura; evita somar áreas partilhadas como independentes.",
      },
      notes: { kind: "longtext", label: "Notas" },
    },
  },
  field_event: {
    name: "field_event",
    table: "field_event",
    label: "Registo de campo",
    labelPlural: "Registos de campo",
    display: ["occurred_on", "event_type"],
    orderBy: "occurred_on desc",
    sheet: "Registos_Campo",
    fields: {
      cycle_id: { kind: "ref", ref: "cycle", label: "Ciclo", required: true },
      occurred_on: { kind: "date", label: "Data do acontecimento", required: true },
      event_type: {
        kind: "enum",
        label: "Tipo",
        required: true,
        values: {
          irrigation: "Irrigação",
          fertilization: "Fertilização",
          growth: "Crescimento",
          pest: "Praga",
          disease: "Doença",
          loss: "Perda",
          maintenance: "Manutenção",
          intervention: "Intervenção",
          photo: "Fotografia",
          note: "Nota",
        },
      },
      value: { kind: "decimal", label: "Valor" },
      unit: { kind: "text", label: "Unidade" },
      origin: origin("measured"),
      method: { kind: "text", label: "Método" },
      description: { kind: "longtext", label: "Descrição" },
    },
  },
  harvest: {
    name: "harvest",
    table: "harvest",
    label: "Colheita",
    labelPlural: "Colheitas",
    display: ["harvest_date"],
    orderBy: "harvest_date",
    sheet: "Colheitas",
    fields: {
      cycle_id: { kind: "ref", ref: "cycle", label: "Ciclo", required: true },
      harvest_date: { kind: "date", label: "Data da colheita", required: true },
      gross_kg: { kind: "decimal", label: "Peso bruto", unit: "kg", min: 0 },
      marketable_kg: { kind: "decimal", label: "Peso comercializável", unit: "kg", min: 0 },
      rejected_kg: { kind: "decimal", label: "Peso rejeitado", unit: "kg", min: 0 },
      units_count: { kind: "int", label: "N.º de unidades/embalagens", min: 0 },
      unit_label: { kind: "text", label: "Unidade comercial (ex.: maço)" },
      destination: {
        kind: "enum",
        label: "Destino",
        values: { stock: "Stock", sale: "Venda", own_consumption: "Consumo próprio", sample: "Amostra", loss: "Perda", mixed: "Misto" },
      },
      origin: origin("measured"),
      method: { kind: "text", label: "Método de pesagem" },
      instrument: { kind: "text", label: "Instrumento" },
      notes: { kind: "longtext", label: "Notas" },
    },
  },
  consumption: {
    name: "consumption",
    table: "consumption",
    label: "Consumo",
    labelPlural: "Consumos",
    display: ["resource", "period_start"],
    orderBy: "period_start",
    sheet: "Consumos",
    fields: {
      resource: { kind: "enum", label: "Recurso", required: true, values: { water: "Água", energy: "Energia", other: "Outro" } },
      structure_id: { kind: "ref", ref: "structure", label: "Estrutura" },
      cycle_id: { kind: "ref", ref: "cycle", label: "Ciclo" },
      period_start: { kind: "date", label: "Início do período" },
      period_end: { kind: "date", label: "Fim do período" },
      reading_start: { kind: "decimal", label: "Leitura inicial do contador" },
      reading_end: { kind: "decimal", label: "Leitura final do contador" },
      quantity: { kind: "decimal", label: "Quantidade consumida" },
      unit: { kind: "enum", label: "Unidade", required: true, values: { L: "L", m3: "m³", Wh: "Wh", kWh: "kWh", h: "h", other: "Outra" } },
      power_w: { kind: "decimal", label: "Potência (para estimar energia)", unit: "W" },
      hours_used: { kind: "decimal", label: "Tempo de utilização", unit: "h" },
      instrument: { kind: "text", label: "Instrumento" },
      origin: origin("measured"),
      notes: { kind: "longtext", label: "Notas" },
    },
  },
  labor_entry: {
    name: "labor_entry",
    table: "labor_entry",
    label: "Trabalho",
    labelPlural: "Trabalho",
    display: ["work_date", "task"],
    orderBy: "work_date",
    sheet: "Trabalho",
    fields: {
      cycle_id: { kind: "ref", ref: "cycle", label: "Ciclo" },
      work_date: { kind: "date", label: "Data", required: true },
      hours: { kind: "decimal", label: "Horas", unit: "h", required: true, min: 0 },
      task: { kind: "text", label: "Tarefa" },
      worker_label: { kind: "text", label: "Quem (designação)" },
      is_paid: { kind: "bool", label: "Trabalho pago", default: false, description: "Separado da valorização do trabalho do autor." },
      hourly_rate: { kind: "decimal", label: "Valor por hora" },
      currency: { ...CURRENCY_FIELD, required: false },
      origin: origin("measured"),
      notes: { kind: "longtext", label: "Notas" },
    },
  },
  asset: {
    name: "asset",
    table: "asset",
    label: "Ativo",
    labelPlural: "Ativos",
    display: ["name"],
    orderBy: "acquired_on",
    sheet: "Ativos",
    fields: {
      name: { kind: "text", label: "Designação", required: true },
      category: { kind: "text", label: "Categoria" },
      acquired_on: { kind: "date", label: "Aquisição" },
      in_use_from: { kind: "date", label: "Entrada em uso" },
      cost: { kind: "decimal", label: "Custo de aquisição", required: true, min: 0 },
      installation_cost: { kind: "decimal", label: "Custo de instalação", min: 0 },
      currency: CURRENCY_FIELD,
      useful_life_months: { kind: "int", label: "Vida útil", unit: "meses", min: 1 },
      residual_value: { kind: "decimal", label: "Valor residual", min: 0 },
      depreciation_method: { kind: "enum", label: "Depreciação", required: true, default: "linear", values: { linear: "Linear", none: "Sem depreciação" } },
      structure_id: { kind: "ref", ref: "structure", label: "Estrutura" },
      notes: { kind: "longtext", label: "Notas" },
    },
  },
  expense: {
    name: "expense",
    table: "expense",
    label: "Despesa",
    labelPlural: "Despesas",
    display: ["expense_date", "description"],
    orderBy: "expense_date",
    sheet: "Despesas",
    fields: {
      expense_date: { kind: "date", label: "Data", required: true },
      category: {
        kind: "enum",
        label: "Categoria",
        required: true,
        values: {
          seeds: "Sementes",
          substrate: "Substratos",
          fertilizer: "Fertilizantes",
          water: "Água",
          energy: "Energia",
          labor: "Trabalho",
          transport: "Transporte",
          packaging: "Embalagem",
          maintenance: "Manutenção",
          other: "Outros",
        },
      },
      description: { kind: "text", label: "Descrição", required: true },
      supplier_private: { kind: "text", label: "Fornecedor (privado)", private: true },
      quantity: { kind: "decimal", label: "Quantidade" },
      unit: { kind: "text", label: "Unidade" },
      unit_price: { kind: "decimal", label: "Preço unitário" },
      tax_amount: { kind: "decimal", label: "Imposto" },
      amount: { kind: "decimal", label: "Valor total", required: true, min: 0 },
      currency: CURRENCY_FIELD,
      cost_behavior: { kind: "enum", label: "Comportamento", required: true, default: "variable", values: { fixed: "Fixo", variable: "Variável" } },
      is_operational: { kind: "bool", label: "Custo operacional", default: true },
      origin: origin("document"),
      replaces_expense_id: {
        kind: "ref",
        ref: "expense",
        label: "Substitui a estimativa",
        description: "Quando uma fatura real substitui um custo estimado: a estimativa deixa de contar.",
      },
      notes: { kind: "longtext", label: "Notas" },
    },
  },
  allocation: {
    name: "allocation",
    table: "allocation",
    label: "Repartição",
    labelPlural: "Repartições",
    display: ["method", "share"],
    orderBy: "created_at",
    sheet: "Reparticoes",
    fields: {
      expense_id: { kind: "ref", ref: "expense", label: "Despesa", required: true },
      cycle_id: { kind: "ref", ref: "cycle", label: "Ciclo", required: true },
      method: {
        kind: "enum",
        label: "Critério",
        required: true,
        values: {
          direct: "Direto (100% do ciclo)",
          area: "Área",
          time: "Tempo",
          measured: "Consumo medido",
          production: "Produção",
          percentage: "Percentagem justificada",
        },
      },
      share: {
        kind: "decimal",
        label: "Fração atribuída",
        unit: "0–1",
        required: true,
        min: 0,
        max: 1,
        description: "Soma das frações de uma despesa não pode exceder 1; a parte não atribuída é mostrada.",
      },
      justification: { kind: "longtext", label: "Justificação do critério" },
    },
  },
  sale: {
    name: "sale",
    table: "sale",
    label: "Venda",
    labelPlural: "Vendas",
    display: ["sale_date", "quantity", "commercial_unit"],
    orderBy: "sale_date",
    sheet: "Vendas",
    fields: {
      cycle_id: { kind: "ref", ref: "cycle", label: "Ciclo" },
      crop_id: { kind: "ref", ref: "crop", label: "Cultura" },
      sale_date: { kind: "date", label: "Data", required: true },
      quantity: { kind: "decimal", label: "Quantidade", required: true, min: 0 },
      commercial_unit: { kind: "text", label: "Unidade comercial", required: true },
      kg_equivalent: { kind: "decimal", label: "Peso equivalente", unit: "kg", description: "Só com fator medido ou pressuposto identificado." },
      kg_equivalent_origin: { kind: "enum", label: "Origem do peso equivalente", values: ORIGINS },
      unit_price: { kind: "decimal", label: "Preço unitário" },
      discount: { kind: "decimal", label: "Desconto" },
      amount: { kind: "decimal", label: "Valor recebido", required: true, min: 0 },
      currency: CURRENCY_FIELD,
      channel: { kind: "text", label: "Canal" },
      notes: { kind: "longtext", label: "Notas" },
    },
  },
  exchange_rate: {
    name: "exchange_rate",
    table: "exchange_rate",
    label: "Taxa de câmbio",
    labelPlural: "Taxas de câmbio",
    display: ["from_currency", "to_currency", "rate_date"],
    orderBy: "rate_date",
    sheet: "Taxas_Cambio",
    fields: {
      from_currency: { kind: "text", label: "De", required: true },
      to_currency: { kind: "text", label: "Para", required: true },
      rate: { kind: "decimal", label: "Taxa", required: true, min: 0 },
      rate_date: { kind: "date", label: "Data", required: true },
      source: { kind: "text", label: "Fonte", required: true },
    },
  },
  excerpt: {
    name: "excerpt",
    table: "excerpt",
    label: "Excerto",
    labelPlural: "Excertos",
    display: ["kind", "locator"],
    orderBy: "created_at",
    fields: {
      reference_id: { kind: "ref", ref: "reference", label: "Fonte", required: true },
      kind: { kind: "enum", label: "Tipo", required: true, values: { literal: "Excerto literal", paraphrase: "Paráfrase", comment: "Comentário do autor" } },
      text: { kind: "longtext", label: "Texto", required: true },
      locator_label: {
        kind: "enum",
        label: "Tipo de localizador",
        values: { page: "Página", paragraph: "Parágrafo", section: "Secção", timestamp: "Tempo", figure: "Figura", table: "Tabela", chapter: "Capítulo" },
      },
      locator: { kind: "text", label: "Localizador (página impressa, parágrafo…)" },
      pdf_page_index: { kind: "int", label: "Página no ficheiro PDF", min: 1, description: "Distinta da página impressa." },
      is_translation: { kind: "bool", label: "Tradução própria", default: false },
      note: { kind: "longtext", label: "Nota" },
    },
  },
  personal_communication: {
    name: "personal_communication",
    table: "personal_communication",
    label: "Comunicação pessoal",
    labelPlural: "Comunicações pessoais",
    display: ["given_initials", "family", "communication_date"],
    orderBy: "communication_date",
    fields: {
      given_initials: { kind: "text", label: "Iniciais do nome próprio (ex.: A. B.)", required: true },
      family: { kind: "text", label: "Apelido", required: true },
      communication_date: { kind: "date", label: "Data", required: true },
      medium: { kind: "text", label: "Meio" },
      authorization_note: { kind: "longtext", label: "Autorização" },
      private_contact: { kind: "text", label: "Contacto (privado)", private: true },
    },
  },
};

export function isEntityName(s: string): s is EntityName {
  return (ENTITY_NAMES as readonly string[]).includes(s);
}
